### ISSUE TITLE
Issues with Prices endpoints

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spice.js#113]
From a user on Discord:
> some scenarios where prices fails to return an array of prices and its resulting in me needing to retry.

Example given:
```shell
curl --location 'https://data.spiceai.io/v0.1/prices/ETH-CAD?preview=true&granularity=5m&start=1679169371' \
--header 'X-API-KEY: $API_KEY'
```
Docs mentioned: https://docs.spice.ai/sdks/node.js-sdk/api-reference

**Comment by Jeadie** [comment]
spice.js is only client with price documentation in https://docs.spice.ai/sdks/node.js-sdk/api-reference. They appear to still reference v0.1 (e.g. `getPrice` is a v0.1 only endpoint).

**Comment by Jeadie** [comment]
Need to
1. Update docs in docs.spice.ai
2. Add docs to [spiceai/spice.js](https://github.com/spiceai/spice.js)

**Comment by Jeadie** [comment]
Updates docs.spice.ai: https://github.com/spicehq/docs/pull/59

**Comment by Jeadie** [comment]
The other issue mentioned in the discord is not getting data for `ETH-CAD`. This is a separate issue.

**Comment by lukekim** [comment]
Closing as we are tracking the -CAD issue elsewhere.
